### ISSUE TITLE
能否提供一个选项设置底部阴影

### ISSUE THREAD

**Issue by yzxzz** [rikumi/iconsur#1]
你好,根据官方提供的bigsur图标模板下方是有阴影和其他细节的,是不是作为一个可选项选择添加/不添加

我导出了一个1024x1024px的透明素材,你可以看下
![画板备份 28](https://user-images.githubusercontent.com/40624194/86882941-a84f3200-c123-11ea-9af9-340e2c7c51c2.png)

**Comment by rikumi** [comment]
在 cf6ece2 中直接实现了，暂时不需要给出选项来关闭。
