### ISSUE TITLE
Use square icons with the mask

### ISSUE THREAD

**Issue by tealbathingsuit** [rikumi/iconsur#11]
Hello, would it be possible to use no mask when the icon is square? I want to apply the round icon effect to an iOS Theme and it would be nice to have that feature. (when using a local square icon it isn't rounded, rather fit and set with a white background)

**Comment by rikumi** [comment]
This is already implemented:

> However, if the original icon is opaque, it will not get scaled down in case you specify an original opaque iOS icon from an app developer or a jailbreak icon pack.
