### ISSUE TITLE
Breaks safari extensions

### ISSUE THREAD

**Issue by tale** [rikumi/iconsur#13]
It seems to disable all of my safari extensions

**Comment by rohmanhm** [comment]
I have to unset the icon and then I can enable the extension again.

cc @rikumi

**Comment by rikumi** [comment]
Are you changing the icon of Safari.app? If so, this should come from Safari checking integrity of contents in Safari.app package which should be a won’t-fix.

**Comment by rohmanhm** [comment]
@rikumi Nope. In my case, I changed the [Lass pass](https://www.lastpass.com) icon. And after run `sudo iconsur cache` the extension is missing from the Safari preferences → Extensions → Left sidebar list and toolbar.
And I have to unset the icon and everything back to normal.

**Comment by rohmanhm** [comment]
Hi @rikumi I think you can close this issue right now, 
I'm able to fix my issue by restarting the app and the safari browser.
