### ISSUE TITLE
Use macosicons.com Icon with IconSur

### ISSUE THREAD

**Issue by raphaelc2009** [rikumi/iconsur#15]
Hello,
Whenever I try to apply an icon from macosicons.com with IconSur, it adds a white background around it. Is there a way to use the icon unmodified?

Thanks in advance.

**Comment by rikumi** [comment]
Add `-s 1` to your command to not get the icon scaled down.

Note that your icon is always getting masked into ‘continuous’ corners to make sure it fits with other icons well.

**Comment by raphaelc2009** [comment]
I have already tried that without success.

**Comment by raphaelc2009** [comment]
-s 1.3 almost works

**Comment by raphaelc2009** [comment]
With icons that have elements going out of the square, it gets cut unfortunately.
Is there a way to simply set an icon from terminal? That way I can do it for some icons and use iconsur for others.

**Comment by rikumi** [comment]
Seems like icons on that website are preprocessed, which means there is already a padding around your icon. In this case please feel free to use [the original fileicon tool](https://github.com/mklement0/fileicon).

**Comment by raphaelc2009** [comment]
Wow thanks!
Now with FileIcon and IconSur all I need is a bash script and I'm ready to go.

**Comment by rikumi** [comment]
Glad you liked my work. IconSur is meant to transform iOS icons or irregular-shaped third-party icons into ones that fit well with Big Sur.

If you already have preprocessed icons, just use them directly.
