### ISSUE TITLE
Telegram Icon Bug

### ISSUE THREAD

**Issue by techgenius1** [rikumi/iconsur#17]
Telegram Icon changes to stock icon when app is running

**Comment by rikumi** [comment]
This is a feature of Telegram to show the latest notification status from the icon while running.

You may use Telegram macOS (instead of Telegram Desktop/Telegram Lite), which already has its icon adapted to Big Sur style.

**Comment by rikumi** [comment]
You can also try replacing the .icns file, which might resolve this kind of issues depending on how the feature is wrote in the app itself. This is totally another way of modifying app icons, which is not covered by this project.

**Comment by techgenius1** [comment]
Oh okay i didnt know that
