### ISSUE TITLE
auto exit when open iconsur

### ISSUE THREAD

**Issue by shreksun** [rikumi/iconsur#19]
![image](https://user-images.githubusercontent.com/48233882/106892626-49888000-6727-11eb-9434-9eac55283518.png)

**Comment by rikumi** [comment]
Do not double-click the binary; call it in terminal according to the usage printed in your screenshot.

不要双击打开，按图上给出的方法在终端里用。

**Comment by shreksun** [comment]
![image](https://user-images.githubusercontent.com/48233882/106983625-2bf7fc80-67a1-11eb-9b67-a73c8ca7e14e.png)
已经添加进路径了 为啥还是找不到呢

**Comment by rikumi** [comment]
PATH 里面写目录名而不是文件

**Comment by shreksun** [comment]
感谢~
