### ISSUE TITLE
ERROR: Cannot modify '/Applications/WhatsApp.app': you do not have write permissions.

### ISSUE THREAD

**Issue by brielov** [rikumi/iconsur#2]
Hi, I'm trying to update the WhatsApp icon on my mac and it throws an error saying I don't have permissions. I guess that this is because it is downloaded from the AppStore. Any idea on how to fix this?

**Comment by SamAkc** [comment]
I'm using the AppStore version as well and for me, it works fine. Are you using "sudo ./iconsur set /Applications/WhatsApp.app"? That did the job for me.
