### ISSUE TITLE
Cannot build on Apple Silicon mac?

### ISSUE THREAD

**Issue by T-Mux** [rikumi/iconsur#24]
It's very strange that the lastest release file can run very well on my M1 sillion Mac a few days ago, but it crashes today after I restart. Then I do the `chmod+x` line but still useless.

\
<img width="1472" alt="截屏2021-03-21 下午1 25 51" src="https://user-images.githubusercontent.com/33898918/111895027-c3ac6400-8a4a-11eb-9863-4fe187ad3455.png">

By the way I've noticed that the release is named "x64", but how can it run well at first?

**Comment by rikumi** [comment]
The binary build comes with a Node binary which is apparently for intel64 architecture.

Instead, you can install Node manually and use the npm build; the homebrew build (#21) should help you with that.

**Comment by IzsakiRobi** [comment]
The screen is contains chmod -x not +x 😊
What terminal you use?

rob

T-Mux ***@***.***> (időpont: 2021. márc. 21., V, 6:41) ezt
írta:

**Comment by rikumi** [comment]
> The screen is contains chmod -x not +x 😊 What terminal you use? rob

@T-Mux  `chmod` is followed by `+x`; also, you should type `./iconsur` if you don't have it in your `PATH`.

**Comment by T-Mux** [comment]
> The binary build comes with a Node binary which is apparently for intel64 architecture.
> 
> Instead, you can install Node manually and use the npm build; the homebrew build (#21) should help you with that.

Thx so much!

**Comment by T-Mux** [comment]
> The screen is contains chmod -x not +x 😊 What terminal you use? rob T-Mux ***@***.***> (időpont: 2021. márc. 21., V, 6:41) ezt írta:

Haha, do u mean the theme I use? [iTerm](https://iterm2.com/) with [Dracula](https://draculatheme.com/) theme

**Comment by IzsakiRobi** [comment]
Thanx for the terminal info 😉
