### ISSUE TITLE
New version of fileicon needed for iconsur to work in macOS 12.3

### ISSUE THREAD

**Issue by westerlind** [rikumi/iconsur#32]
Hi

I am testing the macOS 12.3 beta, and iconsur stopped working there as a consequence of Python 2 being removed, which made fileicon stop working.

I managed to make it work again for myself by simply updating the version of fileicon that is used from https://github.com/mklement0/fileicon and that fixed it, as it does not depend on Python 2 anymore, so I would suggest doing that as a fix.

**Comment by diego-mari** [comment]
Can you describe how to do that?

**Comment by westerlind** [comment]
This is how I did it:

- First, get the source for iconsur, for example like this with git:`git clone https://github.com/rikumi/iconsur.git`
- Then you need to get the new version of fileicon, which is available at https://github.com/mklement0/fileicon and the only file from there that you need is `bin/fileicon` ([here](https://raw.githubusercontent.com/mklement0/fileicon/master/bin/fileicon)), so get that file from there, rename it to fileicon.sh and replace the file called fileicon.sh in the src folder in the iconsur source, and make it executable which you can do for example with this command `chmod +x fileicon.sh`
- Then you need to compile iconsur, and for that you first need `npm`, which I suggest to install with [Homebrew](https://brew.sh) with the command `brew install npm` (assuming you have Homebrew installed), and then you only need to go to the iconsur source folder in a terminal and first type `npm install` and then type `npm run-script build`
- You can now find the compiled iconsur binary in the dist folder that was just created. Place it somewhere in your path, like for example /usr/local/bin/ and make sure to also remove the old version you had that doesn't work anymore, so you don't accidentally use the wrong version
- It should now work again, just like before

**Comment by sshrmr** [comment]
@westerlind hey! could you please explain how to uninstall the old iconsur and install the new compiled one? thanks in advance!

**Comment by LuRenJiasWorld** [comment]
For those who don't want to compile for it, here's the precompiled binary:
[iconsur.zip](https://github.com/rikumi/iconsur/files/8388810/iconsur.zip)
