### ISSUE TITLE
 /usr/bin/python: No such file or directory

### ISSUE THREAD

**Issue by battistinidiego** [rikumi/iconsur#36]
When I try to run sudo iconsur set myAppDir I get this error

/tmp/fileicon-112962.sh: line 203: /usr/bin/python: No such file or directory

**Comment by jasper-buijs** [comment]
I'm having the same issue, although I think this is actually the same problem as #32, even though they don't specify the error there. Issue #32 is about the removal of Python 2 breaking fileicon (though Python3 aka /usr/bin/python3 is still there so an updated version of fileicon should fix this).

Issue #32 also gives a temporary work-around (in the comments), but I warn you it does seem complicated.
