### ISSUE TITLE
White icon background

### ISSUE THREAD

**Issue by josefleventon** [rikumi/iconsur#6]
This seems interesting, but I’d like to know if there’s any way to get an icon background other than white when an App Store icon cannot be found.

**Comment by habovh** [comment]
As per the README, when generating icons from local versions you can set a custom background colour using the `-c` option when invoking `iconsur set`.

> README.md
> ```
> sudo iconsur set /Applications/Visual\ Studio\ Code.app/ -l -s 0.8 -c 87cdf0
> ```
